<a href="https://colab.research.google.com/github/snehal010/010/blob/main/Diabetes_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv


In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('diabetes.csv')

In [ ]:
# print first 5 data
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [ ]:
df.shape

(768, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.size

6912

In [ ]:
df.describe

<bound method NDFrame.describe of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]>

In [ ]:
df.isnull

<bound method DataFrame.isnull of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]>

In [ ]:
df.mean(numeric_only=True)

Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
dtype: float64

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
(df == 0).any()

pregnancies                  True
glucose                     False
bloodpressure               False
skinthickness               False
insulin                     False
bmi                         False
diabetespedigreefunction    False
age                         False
outcome                      True
dtype: bool

In [ ]:
df.columns = df.columns.str.strip().str.lower()

In [ ]:
#columns whre 0 is not a valid medical values
invalid_zero_cols = [
    'glucose',
    'bloodpressure',
    'skinthickness',
    'insulin',
    'bmi'
]

#replace 0 with nan
df[invalid_zero_cols] = df[invalid_zero_cols].replace(0, np.nan)

In [ ]:
#cheking the missing values
df.isnull().sum()

pregnancies                 0
glucose                     0
bloodpressure               0
skinthickness               0
insulin                     0
bmi                         0
diabetespedigreefunction    0
age                         0
outcome                     0
dtype: int64

In [ ]:
#impute missing value_counts
for col in invalid_zero_cols:
    df[col].fillna(df[col].median(), inplace=True)


/tmp/ipython-input-1169701546.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)


In [ ]:

#median represents : a typical patient not too high not  low not
#influnced but outliers

In [ ]:
# feature target seperation

#feature
x = df.drop(columns = ['outcome'])

#target
y = df['outcome']

In [ ]:
x.columns

Index(['pregnancies', 'glucose', 'bloodpressure', 'skinthickness', 'insulin',
       'bmi', 'diabetespedigreefunction', 'age'],
      dtype='object')

In [ ]:
y.name

'outcome'

In [ ]:
# train and test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)


In [ ]:
x_train.shape

(614, 8)

In [ ]:
x_test.shape

(154, 8)

In [ ]:
y.value_counts(normalize=True)

outcome
0    0.651042
1    0.348958
Name: proportion, dtype: float64

In [ ]:
y_train.value_counts(normalize=True)

outcome
0    0.653094
1    0.346906
Name: proportion, dtype: float64

In [ ]:
y_test.value_counts(normalize=True)

outcome
0    0.642857
1    0.357143
Name: proportion, dtype: float64

In [ ]:
# feature scaling
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
#here using logistic regrassion classifier because it is a
#binary classification problem, strong baseline for medical data

from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(x_train_scaled,y_train)
#here now the model trained , uses scaled features, can implement safely

LogisticRegression()

In [ ]:
# prediction
y_pred = log_reg.predict(x_test_scaled)

In [ ]:
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
log_reg.score(x_test_scaled,y_test)

0.7532467532467533

In [ ]:
log_reg.score(x_train_scaled,y_train)

0.7719869706840391

In [ ]:
# linear regrassion probability prediction
y_prob = log_reg.predict_proba(x_test_scaled)

In [ ]:
y_prob[:20]

array([[0.71728313, 0.28271687],
       [0.83606362, 0.16393638],
       [0.89460661, 0.10539339],
       [0.84634265, 0.15365735],
       [0.54099098, 0.45900902],
       [0.55368795, 0.44631205],
       [0.98575091, 0.01424909],
       [0.62421038, 0.37578962],
       [0.42665813, 0.57334187],
       [0.24360418, 0.75639582],
       [0.77865771, 0.22134229],
       [0.11129996, 0.88870004],
       [0.60647622, 0.39352378],
       [0.72132736, 0.27867264],
       [0.92391448, 0.07608552],
       [0.59547239, 0.40452761],
       [0.88852602, 0.11147398],
       [0.92581118, 0.07418882],
       [0.28696241, 0.71303759],
       [0.4276886 , 0.5723114 ]])

In [ ]:
y_prob_diabetic = y_prob[:,1]
y_prob_diabetic[:10]


array([0.28271687, 0.16393638, 0.10539339, 0.15365735, 0.45900902,
       0.44631205, 0.01424909, 0.37578962, 0.57334187, 0.75639582])

In [ ]:
# confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm
#[TN FP]
#[FN TP]

#TN - true negative - actually non diabetic
#FP - false positive - actually non diabetic but predicted diabetic
#FN - false negative - actually diabetic but predicted non diabetic
#TP - true positive - actually diabetic



array([[82, 17],
       [21, 34]])

In [ ]:
#next model we using here is SVM support vector
#machine , it finds a strong,cmargin based decision
#biundry that often improves recall on small

#the main reason to use is defwe did the scaling chance are high to gett better
#recall

In [ ]:
# classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

#here we will see about precision, recall, f1 score and support
#precision: hpw correct the model was when is said 0 or 1
#recall:how many real 0 and 1 it files
#f1:balencescore of precision and recall
#support:how many actual 0 and 1 patients

#example for weighted avg
#classes with more samples influence the final score more
#than the small classes

# Check the first 20 probabilities for the SVM model
y_prob_svm = svm_model.predict_proba(x_test_scaled)
print("\nFirst 20 probability predictions from SVM model:")
print(y_prob_svm[:20])

              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154


First 20 probability predictions from SVM model:
[[0.71043207 0.28956793]
 [0.8175271  0.1824729 ]
 [0.87865317 0.12134683]
 [0.83300141 0.16699859]
 [0.52617407 0.47382593]
 [0.54170324 0.45829676]
 [0.97897372 0.02102628]
 [0.64016197 0.35983803]
 [0.44481781 0.55518219]
 [0.2609178  0.7390822 ]
 [0.7421134  0.2578866 ]
 [0.12714167 0.87285833]
 [0.58863016 0.41136984]
 [0.68056679 0.31943321]
 [0.9152836  0.0847164 ]
 [0.66120522 0.33879478]
 [0.86809991 0.13190009]
 [0.90884494 0.09115506]
 [0.31898289 0.68101711]
 [0.42662769 0.57337231]]


In [ ]:
from sklearn.svm import SVC
svm_model = SVC(kernel = 'linear',probability=True)
svm_model.fit(x_train_scaled,y_train)

SVC(kernel='linear', probability=True)

In [ ]:
y_pred_svm = svm_model.predict(x_test_scaled)
#evaluvating
svm_model.score(x_test_scaled,y_test)



0.7532467532467533

In [ ]:
#confussion matrix
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))
y_prob_svm = svm_model.predict_proba(x_test_scaled)
print("\nFirst 20 probability predictions from SVM model:")
print(y_prob_svm[:20])


              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154


First 20 probability predictions from SVM model:
[[0.71043207 0.28956793]
 [0.8175271  0.1824729 ]
 [0.87865317 0.12134683]
 [0.83300141 0.16699859]
 [0.52617407 0.47382593]
 [0.54170324 0.45829676]
 [0.97897372 0.02102628]
 [0.64016197 0.35983803]
 [0.44481781 0.55518219]
 [0.2609178  0.7390822 ]
 [0.7421134  0.2578866 ]
 [0.12714167 0.87285833]
 [0.58863016 0.41136984]
 [0.68056679 0.31943321]
 [0.9152836  0.0847164 ]
 [0.66120522 0.33879478]
 [0.86809991 0.13190009]
 [0.90884494 0.09115506]
 [0.31898289 0.68101711]
 [0.42662769 0.57337231]]


In [ ]:
#ROC AVC Receiver Operating Characterisite, Area Under the Curve

from sklearn.metrics import roc_auc_score
roc_aur_lr = roc_auc_score(y_test,y_prob[:,1])
roc_aur_svm = roc_auc_score(y_test,y_prob_svm[:,1])

roc_aur_lr,roc_aur_svm

# 81 for both lr and svm
# roc implies that both LR and SVM correctly ranks a diabetic higher
# that a non diabetic 82% for the time
# slides the threshold from 0-1, computes recall and false positives
# at each step, plots the curve

(np.float64(0.8242424242424242), np.float64(0.8249770431588613))

In [ ]:
#ROC AVC Receiver Operating Characterisite, Area Under the Curve

from sklearn.metrics import roc_auc_score
roc_aur_lr = roc_auc_score(y_test,y_prob[:,1])
roc_aur_svm = roc_auc_score(y_test,y_prob_svm[:,1])

roc_aur_lr,roc_aur_svm

# 81 for both lr and svm
# roc implies that both LR and SVM correctly ranks a diabetic higher
# that a non diabetic 82% for the time
# slides the threshold from 0-1, computes recall and false positives
# at each step, plots the curve

(np.float64(0.8242424242424242), np.float64(0.8249770431588613))